base_url = "https://truchip.com"
minify_html = true
output_dir = ".build"
compile_sass = false
build_search_index = false

[markdown]
highlight_code = false

[extra]
# Put all your custom variables here
